name: Deploy Flask API to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/ai-persona-news-crawl-api
          git pull origin main
          source env/bin/activate
          pip install -r requirements.txt
          pkill gunicorn || true
          nohup gunicorn -w 2 -b 0.0.0.0:5000 app:app &
